### ISSUE TITLE
Restructure regression tests

### ISSUE THREAD

**Issue by madbence** [IBM/tekton-lint#25]
Each rule should have its own test file:

- [x] `no-deprecated-resource` #55 
- [x] `no-duplicate-env` #32
- [x] `no-duplicate-param` #35
- [ ] `no-duplicate-resource`
- [x] `no-extra-param` #41
- [x] `no-invalid-name` #56 
- [ ] `no-invalid-param-type`
- [ ] `no-latest-image`
- [ ] `no-missing-param`
- [ ] `no-missing-resource`
- [ ] `no-missing-workspace`
- [ ] `no-pipeline-missing-task`
- [ ] `no-pipeline-task-cycle`
- [ ] `no-resourceversion`
- [ ] `no-undefined-param`
- [ ] `no-undefined-result`
- [ ] `no-undefined-volume`
- [ ] `no-unused-param`
- [ ] `prefer-beta`
- [ ] `prefer-kebab-case`
- [x] `prefer-when-expression` #52
